openapi: 3.0.0
info:
  title: Package Tracking API
  version: 1.0.0
  description: API for managing package tracking, profiles, and addresses.
servers:
  - url: http://localhost:3000/api
paths:
  /packages:
    get:
      summary: Get Packages
      parameters:
        - name: senderId
          in: query
          required: true
          schema:
            type: string
        - name: receiverId
          in: query
          required: true
          schema:
            type: string
        - name: currentCarrierId
          in: query
          required: false
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
        - name: senderAddress
          in: query
          required: false
          schema:
            type: object
            additionalProperties:
              type: string
        - name: receiverAddress
          in: query
          required: false
          schema:
            type: object
            additionalProperties:
              type: string
      responses:
        "200":
          description: A list of packages
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    senderId:
                      type: string
                    receiverId:
                      type: string
                    senderAddressId:
                      type: string
                    receiverAddressId:
                      type: string
                    currentCarrierId:
                      type: string
                    deviceId:
                      type: string
                    status:
                      type: string
                    trackingCode:
                      type: string
                    eta:
                      type: string
    post:
      summary: Create a Package
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                senderId:
                  type: string
                receiverId:
                  type: string
                senderAddressId:
                  type: string
                receiverAddressId:
                  type: string
                currentCarrierId:
                  type: string
                deviceId:
                  type: string
                status:
                  type: string
                trackingCode:
                  type: string
                eta:
                  type: string
      responses:
        "201":
          description: Package created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  senderId:
                    type: string
                  receiverId:
                    type: string
                  senderAddressId:
                    type: string
                  receiverAddressId:
                    type: string
                  currentCarrierId:
                    type: string
                  deviceId:
                    type: string
                  status:
                    type: string
                  trackingCode:
                    type: string
                  eta:
                    type: string

  /packages/{id}:
    get:
      summary: Get Package by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Package details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  senderId:
                    type: string
                  receiverId:
                    type: string
                  senderAddressId:
                    type: string
                  receiverAddressId:
                    type: string
                  currentCarrierId:
                    type: string
                  deviceId:
                    type: string
                  status:
                    type: string
                  trackingCode:
                    type: string
                  eta:
                    type: string

  /addresses:
    post:
      summary: Create an Address
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                street:
                  type: string
                city:
                  type: string
                postalCode:
                  type: string
                country:
                  type: string
      responses:
        "201":
          description: Address created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  street:
                    type: string
                  city:
                    type: string
                  postalCode:
                    type: string
                  country:
                    type: string
