openapi: 3.0.0
info:
  title: Package & Package Tracking API
  version: 1.0.0
  description: API for managing packages, tracking information, logs, and authentication.

servers:
  - url: http://localhost:3000
    description: Local server
  - url: https://t8-server-d2fee2awcybjcqch.swedencentral-01.azurewebsites.net/
    description: Azure Web App (Production)

tags:
  - name: Package
    description: Endpoints for managing packages
  - name: Package Tracking
    description: Endpoints for managing package tracking data
  - name: Logs
    description: Endpoints for managing and viewing backend logs
  - name: Auth
    description: Endpoints for authentication (sign-up and sign-in)

paths:
  /auth/sign-up:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpPayload"
      responses:
        "201":
          description: User registered successfully and token issued
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseAuth"
        "400":
          description: Invalid request body
        "409":
          description: Email or name already taken
        "500":
          description: Internal server error

  /auth/sign-in:
    post:
      tags: [Auth]
      summary: Authenticate user and issue JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignInPayload"
      responses:
        "200":
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponseAuth"
        "400":
          description: Invalid credentials or request body
        "401":
          description: Unauthorized (invalid credentials)
        "500":
          description: Internal server error

  /package:
    get:
      tags: [Package]
      summary: Get packages by sender and receiver
      parameters:
        - in: query
          name: senderId
          required: true
          schema:
            type: integer
          description: Sender profile ID (required)
        - in: query
          name: receiverId
          required: true
          schema:
            type: integer
          description: Receiver profile ID (required)
        - in: query
          name: currentCarrierId
          required: false
          schema:
            type: integer
          description: Current carrier profile ID (optional)
        - in: query
          name: status
          required: false
          schema:
            $ref: "#/components/schemas/PackageStatus"
          description: Filter packages by status (optional)
        - in: query
          name: senderAddress
          required: false
          schema:
            type: string
          description: JSON-stringified address object
          example: '{"street":"Main St","city":"Stockholm","postalCode":"11122","country":"Sweden"}'
        - in: query
          name: receiverAddress
          required: false
          schema:
            type: string
          description: JSON-stringified address object
          example: '{"street":"Main St","city":"Stockholm","postalCode":"11122","country":"Sweden"}'
        - in: query
          name: limit
          required: false
          schema:
            type: integer
          description: Max number of results
        - in: query
          name: readingsLimit
          required: false
          schema:
            type: integer
          description: Limit on tracking readings per package
      responses:
        "200":
          description: List of packages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackageArray"
        "400":
          description: Missing or invalid query params
        "500":
          description: Internal server error

    post:
      tags: [Package]
      summary: Create a new package
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePackagePayload"
      responses:
        "201":
          description: Package created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackage"
        "400":
          description: Invalid request body
        "500":
          description: Internal server error

  /package/{id}:
    get:
      tags: [Package]
      summary: Get package by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: readingsLimit
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Package found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackage"
        "404":
          description: Package not found
        "500":
          description: Internal server error

    patch:
      tags: [Package]
      summary: Step the status of a package by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Package status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackage"
        "400":
          description: Invalid package ID or request
        "500":
          description: Internal server error

  /package/device/{deviceId}:
    get:
      tags: [Package]
      summary: Get package by device ID
      parameters:
        - in: path
          name: deviceId
          required: true
          schema:
            type: string
        - in: query
          name: readingsLimit
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Package found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackage"
        "404":
          description: Package not found
        "500":
          description: Internal server error

  /package-tracking:
    get:
      tags: [Package Tracking]
      summary: Get all package tracking grouped by device
      responses:
        "200":
          description: Tracking records grouped by device
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackageTrackingArray"
        "500":
          description: Internal server error

    post:
      tags: [Package Tracking]
      summary: Create a new package tracking record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackageTracking"
      responses:
        "201":
          description: Package tracking record created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackageTracking"
        "400":
          description: Invalid request body
        "500":
          description: Internal server error

  /package-tracking/{deviceId}:
    get:
      tags: [Package Tracking]
      summary: Get package tracking by device ID
      parameters:
        - in: path
          name: deviceId
          required: true
          schema:
            type: string
        - in: query
          name: latest
          required: false
          schema:
            type: boolean
          description: If true, returns only the latest record
      responses:
        "200":
          description: Tracking records for device
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponsePackageTrackingArray"
        "404":
          description: Device not found
        "500":
          description: Internal server error

  /logs:
    get:
      tags: [Logs]
      summary: Retrieve the backend log file
      description: Returns the log file as `text/plain` for download.
      responses:
        "200":
          description: The log file is returned as text
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: Log file not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      tags: [Logs]
      summary: Clear the backend log file
      description: Empties the log file on the server.
      responses:
        "200":
          description: The log file has been cleared
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Failed to clear the log file
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string

components:
  schemas:
    ApiResponse:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        errors: {}
        data: {}
        token:
          type: string
        success:
          type: boolean

    ApiResponseAuth:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            token:
              type: string

    ApiResponsePackage:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/Package"

    ApiResponsePackageArray:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/Package"

    ApiResponsePackageTracking:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/PackageTracking"

    ApiResponsePackageTrackingArray:
      allOf:
        - $ref: "#/components/schemas/ApiResponse"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/PackageTracking"

    SignUpPayload:
      type: object
      required: [email, name, password, role, companyName]
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        password:
          type: string
        role:
          type: string
        companyName:
          type: string

    SignInPayload:
      type: object
      required: [password]
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        password:
          type: string

    CreatePackagePayload:
      type: object
      required:
        - senderId
        - receiverId
        - currentCarrierId
        - deviceId
        - senderAddress
        - receiverAddress
      properties:
        senderId:
          type: integer
        receiverId:
          type: integer
        currentCarrierId:
          type: integer
        deviceId:
          type: string
        senderAddress:
          $ref: "#/components/schemas/AddressInput"
        receiverAddress:
          $ref: "#/components/schemas/AddressInput"

    Package:
      type: object
      properties:
        id:
          type: integer
        sender:
          $ref: "#/components/schemas/Profile"
        receiver:
          $ref: "#/components/schemas/Profile"
        currentCarrier:
          $ref: "#/components/schemas/Profile"
        senderAddress:
          $ref: "#/components/schemas/Address"
        receiverAddress:
          $ref: "#/components/schemas/Address"
        deviceId:
          type: string
        status:
          $ref: "#/components/schemas/PackageStatus"
        trackingCode:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        eta:
          type: string
          format: date-time
        readings:
          type: array
          items:
            $ref: "#/components/schemas/PackageTracking"

    PackageTracking:
      type: object
      properties:
        id:
          type: integer
        deviceId:
          type: string
        lat:
          type: number
        lng:
          type: number
        temperature:
          type: number
        humidity:
          type: number
        createdAt:
          type: string
          format: date-time

    PackageStatus:
      type: string
      enum:
        - pending
        - in_transit
        - delivered
        - cancelled
        - out_for_delivery

    Profile:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        name:
          type: string
        role:
          type: string
        companyName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Address:
      type: object
      properties:
        id:
          type: integer
        street:
          type: string
        city:
          type: string
        postalCode:
          type: string
        country:
          type: string

    AddressInput:
      type: object
      required: [street, city, postalCode, country]
      properties:
        street:
          type: string
        city:
          type: string
        postalCode:
          type: string
        country:
          type: string
