name: Build and Push Prod Docker Image

on:
  workflow_dispatch:

jobs:
  docker-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build prod Docker image
        run: |
          docker build --target prod -t my-api:latest ./api
          docker tag my-api:latest ${{ secrets.ACR_LOGIN_SERVER }}/my-api:latest

      - name: Push prod image to ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-api:latest
