name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies and build API
      - name: Install and Build API
        run: |
          npm ci --prefix ./api
          npm run build --prefix ./api

      # Log in to Azure Container Registry
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build Docker image for production
      - name: Build Docker image
        run: |
          docker build --target prod -t my-api:latest ./api
          docker tag my-api:latest ${{ secrets.ACR_LOGIN_SERVER }}/my-api:latest

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-api:latest

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./api

  notify-discord:
    needs: docker-build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord deploy message
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            🎉 **Deployment Notification**

            ✅ Code has been successfully deployed to **main**!

            👨‍💻 Deployed by: @${{ github.actor }}
            🏢 Repository: ${{ github.repository }}
            🔗 Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
